version: "3.8"
services:
  app:
    container_name: app
    restart: always
    build: .
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    command: mongod --port 27018
    volumes:
      - ./data:/data/db
    ports:
      - "27018:27018"